# Generated by Django 5.0.1 on 2024-01-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do evento')),
                ('data_evento', models.DateTimeField(verbose_name='Data do evento')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
