# Generated by Django 5.0.1 on 2024-01-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='tarefa_disciplina',
            field=models.TextField(blank=True),
        ),
    ]
