# Generated by Django 5.0.1 on 2024-01-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_anexo'),
        ('usuarios', '0002_disciplina_tarefa_disciplina'),
    ]

    operations = [
    ]
