# Generated by Django 5.0.1 on 2024-01-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_eventos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
    ]
