# Generated by Django 5.0.1 on 2024-01-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_eventos_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_evento',
            field=models.TimeField(null=True),
        ),
    ]
