# Generated by Django 5.0.1 on 2024-01-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_evento_hora_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=100)),
                ('descricao_disciplina', models.TextField(blank=True)),
            ],
        ),
    ]
